# Generated by Django 2.1.2 on 2018-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='message',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='sender_name',
            field=models.CharField(default='mrkai', max_length=128),
        ),
    ]
