# Generated by Django 2.1.2 on 2018-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20181009_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(default=None, max_length=256),
        ),
    ]
