# Generated by Django 2.1 on 2018-10-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20181009_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(default='receiver', max_length=128)),
                ('sender_name', models.CharField(default='sender', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='receiver_name',
            field=models.CharField(default='receiver', max_length=128),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='sender_name',
            field=models.CharField(default='sender', max_length=128),
        ),
    ]
